// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersDatabaseService.Services;

#nullable disable

namespace UsersDatabaseService.Migrations
{
    [DbContext(typeof(UsersDatabaseContext))]
    [Migration("20230114125704_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("UsersDatabaseService.Models.TelegramUserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TelegramUserSettings");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramId")
                        .HasMaxLength(100)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.TelegramUserSettings", b =>
                {
                    b.HasOne("UsersDatabaseService.Models.UserModel", "User")
                        .WithOne("TelegramSettings")
                        .HasForeignKey("UsersDatabaseService.Models.TelegramUserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.UserModel", b =>
                {
                    b.Navigation("TelegramSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
