// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersDatabaseService.Services;

#nullable disable

namespace UsersDatabaseService.Migrations
{
    [DbContext(typeof(UsersDatabaseContext))]
    [Migration("20230114181145_add-fields")]
    partial class addfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("UsersDatabaseService.Models.MonitoringPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangePlatform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GainOrFall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTriggerOnce")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TriggerPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("MonitoringPairs");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.TelegramUserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AntiFloodIntervalAmplification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSetExchange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MorningReport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NightModeEnable")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("NightModeEndsTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("NightModeStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoticationsInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowChangesOnce")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timezone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TelegramUserSettings");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramId")
                        .HasMaxLength(100)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.MonitoringPair", b =>
                {
                    b.HasOne("UsersDatabaseService.Models.UserModel", "Owner")
                        .WithMany("MonitoringPairs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.TelegramUserSettings", b =>
                {
                    b.HasOne("UsersDatabaseService.Models.UserModel", "User")
                        .WithOne("TelegramSettings")
                        .HasForeignKey("UsersDatabaseService.Models.TelegramUserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UsersDatabaseService.Models.UserModel", b =>
                {
                    b.Navigation("MonitoringPairs");

                    b.Navigation("TelegramSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
